#!/bin/sh
set -eu

api_base_url="${API_BASE_URL:-${RETROBOLT_API_BASE_URL:-}}"
debug_ui="${DEBUG_UI:-${RETROBOLT_DEBUG_UI:-0}}"
config_js_path="${CONFIG_JS_PATH:-/usr/share/nginx/html/config.js}"
escaped_api_base_url=$(printf '%s' "$api_base_url" | sed 's/\\/\\\\/g; s/"/\\"/g')
case "$debug_ui" in
  1|true|TRUE|yes|YES|on|ON) debug_ui_json=true ;;
  *) debug_ui_json=false ;;
esac

mkdir -p "$(dirname "$config_js_path")"
cat > "$config_js_path" <<EOF_CONFIG
// Runtime configuration generated by the container entrypoint.
window.__RETROBOLT_ADMIN_CONFIG__ = {
  apiBaseUrl: "$escaped_api_base_url",
  debugUi: $debug_ui_json,
};
EOF_CONFIG
