// Tables
type T_PageSizeOptions = 10 | 25 | 50 | 100
const PAGE_SIZE_OPTIONS: Array<T_PageSizeOptions> = [10, 25, 50, 100]
const DEFAULT_PAGE_SIZE: T_PageSizeOptions = 10
/**
 * Returns full api urls
 * @param path REQUIRES leading slash
 * @returns
 */
const apiUrl = (path: string) => `${process.env.NEXT_PUBLIC_API_BASE_PATH}${path}`

console.log('API Base Path:', process.env.NEXT_PUBLIC_API_BASE_PATH)

enum ErrorCode {
  RESOLUTION_ALREADY_SUBMITTED = 'RESOLUTION_ALREADY_SUBMITTED',
  SCHOOL_RESTRICTED_DATA = 'SCHOOL_RESTRICTED_DATA',
  RESOLUTION_PREVIOUSLY_SUBMITTED_IS_EQUAL_OR_NEWER = 'RESOLUTION_PREVIOUSLY_SUBMITTED_IS_EQUAL_OR_NEWER',
  APPOINTMENT_RESTRICTED_DATA = 'APPOINTMENT_RESTRICTED_DATA',
  STUDENT_RESTRICTED_DATA = 'STUDENT_RESTRICTED_DATA',
  NO_FILE_WAS_PROVIDED = 'NO_FILE_WAS_PROVIDED',
  EVALUATION_RESTRICTED = 'EVALUATION_RESTRICTED',
  UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE',
  QUESTION_BANK_RESTRICTED = 'QUESTION_BANK_RESTRICTED',
}

const LIGHT_BG_COLOR = '#C3D9FF'
const MAIN_BG_COLOR = '#f1f1f1'

const RESOLUTIONS__REMAINING_TIME_WARNING_IN_SECONDS = 5 * 60
// const RESOLUTIONS__REMAINING_TIME_WARNING_IN_SECONDS = 1320

export {
  PAGE_SIZE_OPTIONS,
  DEFAULT_PAGE_SIZE,
  apiUrl,
  ErrorCode,
  LIGHT_BG_COLOR,
  MAIN_BG_COLOR,
  RESOLUTIONS__REMAINING_TIME_WARNING_IN_SECONDS,
}
