name: meta_frontend_prestaging

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.pre_staging
    ports:
      - '3113:3000'
    environment:
      - NODE_ENV=pre_staging
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start
