import { EntityName } from '@/shared/utils'

const APPOINTMENT_NAME = new EntityName({ gender: 'M', plural: 'turnos', singular: 'turno' })
const APPOINTMENT_MAX_STUDENTS = 60
const MAX_APPOINTMENTS_PER_SHIFT = 400

const APPOINTMENT_SCHEDULE_PROFILE_LEGACY = 'legacy_2_blocks'
const APPOINTMENT_SCHEDULE_PROFILE_EXPANDED = 'expanded_6_blocks'

const APPOINTMENT_SLOTS_BY_PROFILE = {
  [APPOINTMENT_SCHEDULE_PROFILE_LEGACY]: [
    [[8, 0], [13, 0]],
    [[13, 0], [18, 0]],
  ],
  [APPOINTMENT_SCHEDULE_PROFILE_EXPANDED]: [
    [[8, 0], [10, 15]],
    [[10, 15], [13, 0]],
    [[13, 0], [16, 15]],
    [[16, 15], [19, 0]],
    [[19, 0], [21, 0]],
    [[21, 0], [23, 0]],
  ],
} as const

const APPOINTMENT_SCHEDULE_PROFILE =
  (process.env.NEXT_PUBLIC_APPOINTMENT_SCHEDULE_PROFILE ?? APPOINTMENT_SCHEDULE_PROFILE_EXPANDED) as keyof typeof APPOINTMENT_SLOTS_BY_PROFILE

export {
  APPOINTMENT_NAME,
  APPOINTMENT_MAX_STUDENTS,
  APPOINTMENT_SCHEDULE_PROFILE,
  APPOINTMENT_SCHEDULE_PROFILE_EXPANDED,
  APPOINTMENT_SCHEDULE_PROFILE_LEGACY,
  APPOINTMENT_SLOTS_BY_PROFILE,
  MAX_APPOINTMENTS_PER_SHIFT,
}
