export const DB_ADMIN_TEST_IDS = {
  loginPage: "rb-login-page",
  loginForm: "rb-login-form",
  loginUsername: "rb-login-username",
  loginPassword: "rb-login-password",
  loginSubmit: "rb-login-submit",
  appShell: "rb-app-shell",
  sidebar: "rb-sidebar",
  main: "rb-main",
  toastRegion: "rb-toast-region",
  workflowNav: "rb-workflow-nav",
  resourceNav: "rb-resource-nav",
  resourceFilter: "rb-resource-filter",
  refreshResources: "rb-refresh-resources",
  signOut: "rb-sign-out",
  resourcePage: "rb-resource-page",
  resourceCreate: "rb-resource-create",
  resourceBatchDelete: "rb-resource-batch-delete",
  resourceRefresh: "rb-resource-refresh",
  resourceQuickSearch: "rb-resource-quick-search",
  resourcePageSize: "rb-resource-page-size",
} as const;

export const BUSINESS_WORKFLOW_TEST_IDS = {
  setupWorkbook: {
    nav: "rb-workflow-setup-workbook-nav",
    page: "rb-setup-workbook-page",
    templateButton: "rb-setup-workbook-template",
    draftButton: "rb-setup-workbook-draft",
    fileInput: "rb-setup-workbook-file",
    dryRunButton: "rb-setup-workbook-dry-run",
    previewButton: "rb-setup-workbook-preview",
    auditStageButton: "rb-setup-workbook-audit-stage",
    runtimeCommitButton: "rb-setup-workbook-runtime-commit",
    reasonInput: "rb-setup-workbook-reason",
    manifestCard: "rb-setup-workbook-manifest",
    dryRunResult: "rb-setup-workbook-dry-run-result",
    commitPlan: "rb-setup-workbook-commit-plan",
    auditStageResult: "rb-setup-workbook-audit-stage-result",
    runtimeCommitResult: "rb-setup-workbook-runtime-commit-result",
  },
  matrixEditor: {
    nav: "rb-workflow-matrix-editor-nav",
    page: "rb-matrix-editor-page",
    domainSelect: "rb-matrix-domain-select",
    loadUniverseButton: "rb-matrix-load-universe",
    validateButton: "rb-matrix-validate",
    previewButton: "rb-matrix-preview",
    applyButton: "rb-matrix-apply",
  },
  auditView: {
    nav: "rb-workflow-audit-nav",
    page: "rb-audit-page",
  },
  manualScoring: {
    nav: "rb-workflow-manual-scoring-nav",
    page: "rb-manual-scoring-page",
    reloadButton: "rb-manual-scoring-reload",
    stateFilter: "rb-manual-scoring-state-filter",
    queue: "rb-manual-scoring-queue",
    scoreForm: "rb-manual-scoring-form",
    submitButton: "rb-manual-scoring-submit",
    textAnnotationEditor: "rb-manual-scoring-text-annotation-editor",
    releaseCorrectionButton: "rb-manual-scoring-release-correction",
  },
  reportExports: {
    page: "rb-report-exports-page",
    createButton: "rb-report-export-create",
    downloadButton: "rb-report-export-download",
    revokeButton: "rb-report-export-revoke",
    status: "rb-report-export-status",
    fileMetadata: "rb-report-export-file-metadata",
  },
} as const;

export const FUTURE_BUSINESS_FRONTEND_TEST_IDS = {
  studentExam: {
    entryPage: "rb-student-exam-entry-page",
    authorizeForm: "rb-student-exam-authorize-form",
    personalIdInput: "rb-student-exam-personal-id",
    authorizeSubmit: "rb-student-exam-authorize-submit",
    shell: "rb-student-exam-shell",
    content: "rb-student-exam-content",
    questionNavigation: "rb-student-exam-question-navigation",
    questionPrompt: "rb-student-exam-question-prompt",
    answerArea: "rb-student-exam-answer-area",
    autosaveStatus: "rb-student-exam-autosave-status",
    submitButton: "rb-student-exam-submit",
    offlineStatus: "rb-student-exam-offline-status",
    supportDrawer: "rb-student-self-service-support-drawer",
    accessibilityControls: "rb-student-accessibility-controls",
    downloadControls: "rb-student-download-controls",
    supportControls: "rb-student-support-controls",
    correctionView: "rb-student-correction-view",
    correctionQuestion: "rb-student-correction-question",
    correctionAnnotation: "rb-student-correction-annotation",
    correctionScoreSource: "rb-student-correction-score-source",
    correctionCorrectAnswer: "rb-student-correction-correct-answer",
    returnFocusTarget: "rb-student-exam-focus-target",
  },
  guestPreview: {
    previewShell: "rb-guest-preview-shell",
    datasetSelector: "rb-guest-preview-dataset-selector",
    resetPreview: "rb-guest-preview-reset",
    demoExportWatermark: "rb-guest-preview-demo-export-watermark",
  },
} as const;
