name: Deploy to Azure - MetaApp-Web

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip source code
        run: zip -r app.zip . -x ".git/*" "node_modules/*" ".github/*" ".next/*"

      - name: Upload to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MetaApp-Website'
          slot-name: 'Production'
          package: app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4975FA1D14654DA384E94A6FFD5C4E8C }}
